---
# ValidatingAdmissionPolicy para proibir Deployments no namespace default
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: deny-deployments-default-namespace
spec:
  failurePolicy: fail
  scope: Namespaced
  rules:
  - apiGroups:
    - "apps"
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - statefulsets
    - daemonsets
    - replicasets
    scope: "Namespaced"
  matchConditions:
  - name: "is-default-namespace"
    expression: "object.metadata.namespace == 'default'"
  validations:
  - expression: "false"
    message: "NÃO é permitido fazer deploy de aplicações no namespace 'default'. Use um namespace dedicado."

---
# ValidatingAdmissionPolicyBinding para aplicar a política de rejeição
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-deployments-default-namespace-binding
spec:
  policyName: deny-deployments-default-namespace
  validationActions:
  - deny
