---
# Namespace para Edge 1
apiVersion: v1
kind: Namespace
metadata:
  name: teste-2
  labels:
    app: teste-2
    environment: production
    cluster: edge-1
  annotations:
    description: "Namespace para testes de root-sync no Edge 1"
    cluster-region: "global"

---
# Namespace para Edge 2
apiVersion: v1
kind: Namespace
metadata:
  name: root-sync-teste
  labels:
    app: root-sync-teste
    environment: production
    cluster: edge-2
  annotations:
    description: "Namespace para testes de root-sync no Edge 2"
    cluster-region: "global"
